// OpenTelemetry bootstrap — generated by otel-as-code. Re-run /otel-instrument to regenerate.
// Semconv version: 1.44.0
//
// Exports traces, metrics and logs over OTLP/HTTP (protobuf, port 4318) when
// OTEL_EXPORTER_OTLP_ENDPOINT is set. With no endpoint it installs only a stdout log
// subscriber and exports nothing, so an unconfigured deployment stays quiet instead of
// retrying localhost forever. Keep the guard returned by `init()` alive for the life of
// the process: dropping it flushes and shuts down every provider.
use opentelemetry::{global, trace::TracerProvider as _, KeyValue};
use opentelemetry_appender_tracing::layer::OpenTelemetryTracingBridge;
use opentelemetry_otlp::{LogExporter, MetricExporter, Protocol, SpanExporter, WithExportConfig};
use opentelemetry_sdk::{
    logs::SdkLoggerProvider, metrics::SdkMeterProvider, propagation::TraceContextPropagator,
    trace::SdkTracerProvider, Resource,
};
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt, EnvFilter, Layer};

pub struct TelemetryGuard {
    tracer_provider: Option<SdkTracerProvider>,
    meter_provider: Option<SdkMeterProvider>,
    logger_provider: Option<SdkLoggerProvider>,
}

impl Drop for TelemetryGuard {
    fn drop(&mut self) {
        if let Some(p) = self.tracer_provider.take() {
            let _ = p.shutdown();
        }
        if let Some(p) = self.meter_provider.take() {
            let _ = p.shutdown();
        }
        if let Some(p) = self.logger_provider.take() {
            let _ = p.shutdown();
        }
    }
}

fn resource() -> Resource {
    let env = |key: &str, default: &str| std::env::var(key).unwrap_or_else(|_| default.to_string());
    Resource::builder()
        .with_service_name(env("OTEL_SERVICE_NAME", "search-api"))
        .with_attributes([
            KeyValue::new("service.version", env("OTEL_SERVICE_VERSION", "0.4.0")),
            // Emit service.namespace only when the context has a confirmed namespace;
            // otherwise delete this line rather than emit a placeholder.
            KeyValue::new(
                "service.namespace",
                env("OTEL_SERVICE_NAMESPACE", "storefront"),
            ),
            KeyValue::new(
                "deployment.environment.name",
                env("DEPLOYMENT_ENV", "development"),
            ),
        ])
        .build()
}

pub fn init() -> TelemetryGuard {
    let fmt_layer = tracing_subscriber::fmt::layer()
        .with_filter(EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")));

    // Only the shared endpoint turns export on: every exporter below falls back to it, while a
    // per-signal endpoint alone (e.g. only *_TRACES_ENDPOINT) would leave the others on localhost.
    let endpoint_set = std::env::var("OTEL_EXPORTER_OTLP_ENDPOINT").is_ok_and(|v| !v.is_empty());
    if !endpoint_set {
        tracing_subscriber::registry().with(fmt_layer).init();
        tracing::warn!(
            "[otel] OTEL_EXPORTER_OTLP_ENDPOINT is not set, so this process exports no telemetry"
        );
        return TelemetryGuard {
            tracer_provider: None,
            meter_provider: None,
            logger_provider: None,
        };
    }

    // The tower layer extracts incoming `traceparent` headers through the global propagator,
    // which is a no-op until one is set.
    global::set_text_map_propagator(TraceContextPropagator::new());
    let resource = resource();

    // Metrics (Stable).
    let meter_provider = SdkMeterProvider::builder()
        .with_periodic_exporter(
            MetricExporter::builder()
                .with_http()
                .with_protocol(Protocol::HttpBinary)
                .build()
                .expect("OTLP metric exporter"),
        )
        .with_resource(resource.clone())
        .build();
    global::set_meter_provider(meter_provider.clone());

    // Traces (Beta signal — API may change in future OTel releases).
    let tracer_provider = SdkTracerProvider::builder()
        .with_batch_exporter(
            SpanExporter::builder()
                .with_http()
                .with_protocol(Protocol::HttpBinary)
                .build()
                .expect("OTLP span exporter"),
        )
        .with_resource(resource.clone())
        .build();
    global::set_tracer_provider(tracer_provider.clone());
    let tracer = tracer_provider.tracer("search-api");

    // Logs (Stable): `tracing` events are bridged into OTel log records.
    let logger_provider = SdkLoggerProvider::builder()
        .with_batch_exporter(
            LogExporter::builder()
                .with_http()
                .with_protocol(Protocol::HttpBinary)
                .build()
                .expect("OTLP log exporter"),
        )
        .with_resource(resource)
        .build();
    // The exporter's own HTTP stack logs through `tracing` too; exporting those records would
    // produce more of them. Same target list as the upstream opentelemetry-otlp example.
    let otel_logs_filter = EnvFilter::new("info")
        .add_directive("hyper=off".parse().unwrap())
        .add_directive("tonic=off".parse().unwrap())
        .add_directive("h2=off".parse().unwrap())
        .add_directive("reqwest=off".parse().unwrap());

    tracing_subscriber::registry()
        .with(fmt_layer)
        .with(tracing_opentelemetry::layer().with_tracer(tracer))
        .with(OpenTelemetryTracingBridge::new(&logger_provider).with_filter(otel_logs_filter))
        .init();

    TelemetryGuard {
        tracer_provider: Some(tracer_provider),
        meter_provider: Some(meter_provider),
        logger_provider: Some(logger_provider),
    }
}
