// instrumentation.js — OpenTelemetry register hook, generated by otel-as-code v0.1.0
// Re-run /otel-instrument to regenerate. Server-side only; browser/RUM is out of scope.
//
// Next.js calls register() once per server instance (auto-detected in Next.js 15+; for 13.4–14.x
// enable experimental.instrumentationHook in next.config). @vercel/otel handles the Node/Edge
// runtime split and is driven by the OTEL_* env vars. NOTE: @vercel/otel exports over OTLP/HTTP
// only — point OTEL_EXPORTER_OTLP_ENDPOINT at the collector's HTTP port (4318), not gRPC 4317.
import { registerOTel } from "@vercel/otel";

export function register() {
  registerOTel({ serviceName: process.env.OTEL_SERVICE_NAME || "web-frontend" });
}
