# OpenTelemetry SDK bootstrap — generated by otel-as-code v0.1.0
# Semconv version: 1.44.0
# Re-run /otel-instrument to regenerate.
import os
from opentelemetry import trace, metrics
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.metrics.export import PeriodicExportingMetricReader
from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
from opentelemetry.exporter.otlp.proto.grpc.metric_exporter import OTLPMetricExporter
from opentelemetry.sdk.resources import Resource
from opentelemetry.semconv.resource import ResourceAttributes

# `deployment.environment` was renamed to `deployment.environment.name`. That attribute
# is still incubating, so its constant is not in the stable ResourceAttributes class; use
# the current string literal so this matches the Node bootstrap (which emits the same key).
_DEPLOYMENT_ENVIRONMENT_NAME = "deployment.environment.name"

_endpoint = os.getenv("OTEL_EXPORTER_OTLP_ENDPOINT", "http://localhost:4317")

resource = Resource.create({
    ResourceAttributes.SERVICE_NAME: os.getenv("OTEL_SERVICE_NAME", "inventory-api"),
    ResourceAttributes.SERVICE_VERSION: os.getenv("OTEL_SERVICE_VERSION", "0.3.1"),
    # Emit service.namespace only when the context JSON has a confirmed namespace; omit otherwise.
    ResourceAttributes.SERVICE_NAMESPACE: os.getenv("OTEL_SERVICE_NAMESPACE", "storefront"),
    _DEPLOYMENT_ENVIRONMENT_NAME: os.getenv("DEPLOYMENT_ENV", "development"),
})

# Traces
_tracer_provider = TracerProvider(resource=resource)
_tracer_provider.add_span_processor(
    BatchSpanProcessor(OTLPSpanExporter(endpoint=_endpoint))
)
trace.set_tracer_provider(_tracer_provider)

# Metrics
_metric_reader = PeriodicExportingMetricReader(
    OTLPMetricExporter(endpoint=_endpoint),
    export_interval_millis=30_000,
)
_meter_provider = MeterProvider(resource=resource, metric_readers=[_metric_reader])
metrics.set_meter_provider(_meter_provider)


def instrument_fastapi(app):
    """Call this after creating your FastAPI app instance."""
    from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
    FastAPIInstrumentor.instrument_app(app)
    return app


def shutdown():
    _tracer_provider.shutdown()
    _meter_provider.shutdown()
