// tracing.go — OpenTelemetry SDK bootstrap, generated by otel-as-code v0.1.0
// Semconv version: 1.44.0
// Re-run /otel-instrument to regenerate.

package main

import (
	"context"
	"errors"
	"os"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploggrpc"
	"go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc"
	"go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
	logglobal "go.opentelemetry.io/otel/log/global"
	sdklog "go.opentelemetry.io/otel/sdk/log"
	sdkmetric "go.opentelemetry.io/otel/sdk/metric"
	sdkresource "go.opentelemetry.io/otel/sdk/resource"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
)

func envOrDefault(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func newResource(ctx context.Context) (*sdkresource.Resource, error) {
	return sdkresource.New(ctx,
		sdkresource.WithAttributes(
			attribute.String("service.name", envOrDefault("OTEL_SERVICE_NAME", "search-api")),
			attribute.String("service.version", envOrDefault("OTEL_SERVICE_VERSION", "2.0.0")),
			attribute.String("service.namespace", envOrDefault("OTEL_SERVICE_NAMESPACE", "storefront")),
			attribute.String("deployment.environment.name", envOrDefault("DEPLOYMENT_ENV", "development")),
		),
	)
}

// InitOtel bootstraps the OpenTelemetry SDK for traces and metrics. If
// OTEL_EXPORTER_OTLP_ENDPOINT is unset, no exporter/provider is registered
// and the global API remains a no-op — this deployment exports nowhere until
// the endpoint is configured, matching Node/Python's "exports nowhere until
// configured" default rather than .NET/Java's "defaults to localhost:4317
// and retries". The returned shutdown func is always safe to call, even if
// no providers were created.
func InitOtel(ctx context.Context) (shutdown func(context.Context) error, err error) {
	endpoint := os.Getenv("OTEL_EXPORTER_OTLP_ENDPOINT")
	if endpoint == "" {
		return func(context.Context) error { return nil }, nil
	}

	res, err := newResource(ctx)
	if err != nil {
		return func(context.Context) error { return nil }, err
	}

	var shutdownFuncs []func(context.Context) error
	shutdown = func(ctx context.Context) error {
		var errs error
		for _, fn := range shutdownFuncs {
			if err := fn(ctx); err != nil {
				errs = errors.Join(errs, err)
			}
		}
		return errs
	}

	traceExporter, err := otlptracegrpc.New(ctx,
		otlptracegrpc.WithEndpointURL(endpoint),
	)
	if err != nil {
		return shutdown, err
	}

	tracerProvider := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(traceExporter),
		sdktrace.WithResource(res),
	)
	shutdownFuncs = append(shutdownFuncs, tracerProvider.Shutdown)
	otel.SetTracerProvider(tracerProvider)

	metricExporter, err := otlpmetricgrpc.New(ctx,
		otlpmetricgrpc.WithEndpointURL(endpoint),
	)
	if err != nil {
		return shutdown, err
	}

	meterProvider := sdkmetric.NewMeterProvider(
		sdkmetric.WithReader(sdkmetric.NewPeriodicReader(metricExporter)),
		sdkmetric.WithResource(res),
	)
	shutdownFuncs = append(shutdownFuncs, meterProvider.Shutdown)
	otel.SetMeterProvider(meterProvider)

	return shutdown, nil
}

// ---------------------------------------------------------------------------
// Logs (Beta signal — API may change in future OTel releases). Generated by
// default (Beta does not require --experimental), but kept out of InitOtel's
// required path and wired only from this separate, clearly-marked block —
// call InitOtelLogsBeta explicitly (in addition to InitOtel) to enable it.
// Like InitOtel, it is a no-op when OTEL_EXPORTER_OTLP_ENDPOINT is unset.
// ---------------------------------------------------------------------------

// InitOtelLogsBeta bootstraps the OpenTelemetry Logs SDK (Beta) and installs
// it as the global LoggerProvider via go.opentelemetry.io/otel/log/global —
// the Logs API does not yet expose a setter on go.opentelemetry.io/otel
// itself the way traces/metrics do; log/global is an explicitly-experimental
// shim until the Logs API stabilizes. The returned shutdown func is always
// safe to call, even if no provider was created.
func InitOtelLogsBeta(ctx context.Context) (shutdown func(context.Context) error, err error) {
	endpoint := os.Getenv("OTEL_EXPORTER_OTLP_ENDPOINT")
	if endpoint == "" {
		return func(context.Context) error { return nil }, nil
	}

	res, err := newResource(ctx)
	if err != nil {
		return func(context.Context) error { return nil }, err
	}

	logExporter, err := otlploggrpc.New(ctx,
		otlploggrpc.WithEndpointURL(endpoint),
	)
	if err != nil {
		return func(context.Context) error { return nil }, err
	}

	loggerProvider := sdklog.NewLoggerProvider(
		sdklog.WithProcessor(sdklog.NewBatchProcessor(logExporter)),
		sdklog.WithResource(res),
	)
	logglobal.SetLoggerProvider(loggerProvider)

	return loggerProvider.Shutdown, nil
}
