#!/usr/bin/env bash
# tests/hooks/force-scope.test.sh
# Locks the #169 contract: --force may overwrite only files that carry the ownership marker.
# The scanner's bootstrapFiles list used to sweep in a framework hook and API call-site helpers
# ("any helper module beside it"), and /otel-instrument Step 4 trusted that list as the overwrite
# set, so --force offered hand-written app code for regeneration and wrote it into the sentinel.
set -uo pipefail
cd "$(dirname "$0")/../.."
pass=0; fail=0
check() { if eval "$2"; then echo "PASS: $1"; pass=$((pass+1)); else echo "FAIL: $1"; fail=$((fail+1)); fi; }

SCANNER="agents/repo-context-scanner.md"
AUDITOR="agents/brownfield-auditor.md"
EVAL="commands/otel-evaluate.md"
INSTR="commands/otel-instrument.md"
FIX="fixtures/nextjs-brownfield-api-helper"

STEP4=$(sed -n '/^## Step 4: Find the existing artifact/,/^## Step 5/p' "$INSTR")   # captured once: grep -q + pipefail would race

# --- scanner: bootstrapFiles is SDK construction only; call sites get their own field ---
check "scanner: bootstrapFiles holds files that construct or configure an SDK" \
  'grep -q "construct or configure an SDK" "$SCANNER"'
check "scanner: framework hook, API-only helpers and custom processors are kept out" \
  'grep -q "Keep these OUT of \`bootstrapFiles\`" "$SCANNER" && grep -q "framework hook that only imports the bootstrap" "$SCANNER" && grep -q "sampler or exporter class" "$SCANNER"'
check "scanner: apiCallSites is defined and is in the schema example" \
  'grep -q "^   - \`apiCallSites\`" "$SCANNER" && grep -q "\"apiCallSites\": \[\]" "$SCANNER"'
check "scanner: records every importer of a call-site helper" \
  'grep -q "importers of each call-site" "$SCANNER"'

# --- consumers ---
check "evaluate reads apiCallSites as well as bootstrapFiles" \
  'grep -q "existingOtel.apiCallSites" "$EVAL"'
check "auditor input list names apiCallSites" \
  'grep -q "bootstrapFiles\`, \`apiCallSites\`" "$AUDITOR"'

# --- /otel-instrument Step 4: ownership split ---
step4_has() { grep -qF -- "$1" <<<"$STEP4"; }
check "instrument no longer treats bootstrapFiles as 'the answer' for what to overwrite" \
  '! step4_has "that is the answer"'
check "instrument splits found files by the ownership marker" \
  'step4_has "generated by otel-as-code" && step4_has "hand-written"'
check "instrument: hand-written paths stay out of existingArtifacts, the warning and the sentinel" \
  'step4_has "Never put a hand-written path in \`existingArtifacts\`" && step4_has ".claude/.otel-force"'
check "instrument: hand-written-only brownfield exits with an accurate message, --force or not" \
  'step4_has "already configures OpenTelemetry by hand" && step4_has "Nothing was written"'
check "instrument: the sentinel lists generated paths only" \
  'grep -qF "List the GENERATED paths resolved in this step" "$INSTR"'

# --- fixture: one file per role, none of them generated ---
check "fixture: the bootstrap constructs the SDK" \
  'grep -q "new NodeSDK" "$FIX/src/telemetry.node.ts"'
check "fixture: the framework hook only imports the bootstrap" \
  'grep -q "import(\"./telemetry.node\")" "$FIX/src/instrumentation.ts" && ! grep -q "new NodeSDK" "$FIX/src/instrumentation.ts"'
check "fixture: the call-site helper uses the Logs API and constructs no provider" \
  'grep -q "@opentelemetry/api-logs" "$FIX/src/lib/log-exception.ts" && ! grep -qE "NodeSDK|LoggerProvider|TracerProvider" "$FIX/src/lib/log-exception.ts"'
check "fixture: the helper has two importers (the hook and a route handler)" \
  '[ "$(grep -rl "log-exception" "$FIX/src" | grep -v "lib/log-exception.ts" | wc -l)" -eq 2 ]'
check "fixture: nothing in it carries the ownership marker" \
  '! grep -rq "generated by otel-as-code" "$FIX"'

echo ""
echo "Results: $pass passed, $fail failed"
[ "$fail" -eq 0 ]
