#!/usr/bin/env bash
# tests/hooks/write-guard.test.sh
# Tests for the write-guard PreToolUse hook.
# Usage: bash tests/hooks/write-guard.test.sh
set -euo pipefail

HOOK="hooks/write-guard.sh"
PASS=0
FAIL=0

# On MSYS / Git Bash (the Windows CI job), an ABSOLUTE mktemp temp path (`/tmp/…` or a Git-Bash
# mount) does not round-trip through the NATIVE Windows python the hook runs under — native python
# resolves MSYS `/tmp` to `C:\tmp`, so a temp-path force-match cannot be exercised faithfully here.
# Real `--force` usage under a repo path IS covered on Windows by the "matches a Windows path
# against its Git Bash spelling" case and the relative-entry cases (all of which pass on Windows).
# So the handful of ABSOLUTE-temp-path force cases below are skipped on MSYS only; they run in full
# on Linux/macOS. See PR for #55.
IS_MSYS=0
case "$(uname -s 2>/dev/null)" in MINGW*|MSYS*|CYGWIN*) IS_MSYS=1 ;; esac

run_test() {
  local name="$1"; local input="$2"; local expect_exit="$3"
  actual_exit=0
  echo "$input" | bash "$HOOK" > /dev/null 2>&1 || actual_exit=$?
  if [ "$actual_exit" -eq "$expect_exit" ]; then
    echo "PASS: $name"
    PASS=$((PASS+1))
  else
    echo "FAIL: $name (expected exit $expect_exit, got $actual_exit)"
    FAIL=$((FAIL+1))
  fi
}

# Test 1: Write to a non-OTel file → allow (exit 0)
run_test "allow non-otel file" \
  '{"tool_name":"Write","tool_input":{"file_path":"src/utils.js"}}' 0

# Test 2: Write to tracing.js when it exists → block (exit 2)
TMP=$(mktemp -d)
printf '# generated by otel-as-code v0.1.0\nexisting content\n' >"$TMP/tracing.js"
INPUT="{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"$TMP/tracing.js\"}}"
actual_exit=0
echo "$INPUT" | bash "$HOOK" > /dev/null 2>&1 || actual_exit=$?
if [ "$actual_exit" -eq 2 ]; then
  echo "PASS: block existing tracing.js"
  PASS=$((PASS+1))
else
  echo "FAIL: block existing tracing.js (expected 2, got $actual_exit)"
  FAIL=$((FAIL+1))
fi
rm -rf "$TMP"

# Test 3: Write to infra/observability/datadog/main.tf when it exists → block (exit 2)
TMP=$(mktemp -d)
mkdir -p "$TMP/infra/observability/datadog"
printf '# Generated by otel-as-code v0.1.0\nexisting tf\n' >"$TMP/infra/observability/datadog/main.tf"
INPUT="{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"$TMP/infra/observability/datadog/main.tf\"}}"
actual_exit=0
echo "$INPUT" | bash "$HOOK" > /dev/null 2>&1 || actual_exit=$?
if [ "$actual_exit" -eq 2 ]; then
  echo "PASS: block existing terraform file"
  PASS=$((PASS+1))
else
  echo "FAIL: block existing terraform file (expected 2, got $actual_exit)"
  FAIL=$((FAIL+1))
fi
rm -rf "$TMP"

# Test 4: OTEL_FORCE=1 env override → allow (exit 0)
TMP=$(mktemp -d)
printf '# generated by otel-as-code v0.1.0\nexisting content\n' >"$TMP/tracing.js"
INPUT="{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"$TMP/tracing.js\"}}"
actual_exit=0
echo "$INPUT" | OTEL_FORCE=1 bash "$HOOK" > /dev/null 2>&1 || actual_exit=$?
if [ "$actual_exit" -eq 0 ]; then
  echo "PASS: OTEL_FORCE env override allows overwrite"
  PASS=$((PASS+1))
else
  echo "FAIL: OTEL_FORCE env override (expected 0, got $actual_exit)"
  FAIL=$((FAIL+1))
fi
rm -rf "$TMP"

# Test 5: .claude/.otel-force sentinel lists this path → allow (exit 0)
TMP=$(mktemp -d)
printf '# generated by otel-as-code v0.1.0\nexisting content\n' >"$TMP/tracing.js"
mkdir -p "$TMP/.claude"
echo "$TMP/tracing.js" > "$TMP/.claude/.otel-force"
INPUT="{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"$TMP/tracing.js\"}}"
actual_exit=0
echo "$INPUT" | CLAUDE_PROJECT_DIR="$TMP" bash "$HOOK" > /dev/null 2>&1 || actual_exit=$?
if [ "$actual_exit" -eq 0 ]; then
  echo "PASS: --force sentinel allows the listed path"
  PASS=$((PASS+1))
elif [ "$IS_MSYS" = 1 ]; then
  echo "SKIP (MSYS, absolute temp path): --force sentinel allows the listed path"
else
  echo "FAIL: --force sentinel (expected 0, got $actual_exit)"
  FAIL=$((FAIL+1))
fi
rm -rf "$TMP"

# Test 6: sentinel exists but does NOT list this path → still block (exit 2)
# Proves --force is path-scoped and never blanket-disables the guard.
TMP=$(mktemp -d)
printf '# generated by otel-as-code v0.1.0\nexisting content\n' >"$TMP/tracing.js"
mkdir -p "$TMP/.claude"
echo "$TMP/unrelated.js" > "$TMP/.claude/.otel-force"
INPUT="{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"$TMP/tracing.js\"}}"
actual_exit=0
echo "$INPUT" | CLAUDE_PROJECT_DIR="$TMP" bash "$HOOK" > /dev/null 2>&1 || actual_exit=$?
if [ "$actual_exit" -eq 2 ]; then
  echo "PASS: --force sentinel does not blanket-disable the guard"
  PASS=$((PASS+1))
else
  echo "FAIL: --force path-scoping (expected 2, got $actual_exit)"
  FAIL=$((FAIL+1))
fi
rm -rf "$TMP"

# Test 7: writing otel-context.json with an UNCONFIRMED business attr → block (exit 2)
TMP=$(mktemp -d); mkdir -p "$TMP/.claude"
CTX='{"schemaVersion":"1","businessAttrs":[{"name":"biz.checkout.conversion_rate","confirmed":false}]}'
INPUT=$(python3 -c "import json,sys; print(json.dumps({'tool_name':'Write','tool_input':{'file_path':sys.argv[1],'content':sys.argv[2]}}))" "$TMP/.claude/otel-context.json" "$CTX")
actual_exit=0
echo "$INPUT" | bash "$HOOK" > /dev/null 2>&1 || actual_exit=$?
if [ "$actual_exit" -eq 2 ]; then
  echo "PASS: blocks unconfirmed business attribute write"
  PASS=$((PASS+1))
else
  echo "FAIL: unconfirmed business attr (expected 2, got $actual_exit)"
  FAIL=$((FAIL+1))
fi
rm -rf "$TMP"

# Test 8: writing otel-context.json with ALL business attrs confirmed → allow (exit 0)
TMP=$(mktemp -d); mkdir -p "$TMP/.claude"
CTX='{"schemaVersion":"1","businessAttrs":[{"name":"biz.checkout.conversion_rate","confirmed":true}]}'
INPUT=$(python3 -c "import json,sys; print(json.dumps({'tool_name':'Write','tool_input':{'file_path':sys.argv[1],'content':sys.argv[2]}}))" "$TMP/.claude/otel-context.json" "$CTX")
actual_exit=0
echo "$INPUT" | bash "$HOOK" > /dev/null 2>&1 || actual_exit=$?
if [ "$actual_exit" -eq 0 ]; then
  echo "PASS: allows fully-confirmed business attrs"
  PASS=$((PASS+1))
else
  echo "FAIL: confirmed business attrs (expected 0, got $actual_exit)"
  FAIL=$((FAIL+1))
fi
rm -rf "$TMP"

# Test 9: Write to otel-java.env (the generated Java agent config) when it exists → block (exit 2)
TMP=$(mktemp -d)
printf '# OpenTelemetry Java agent config — generated by otel-as-code v0.1.0\nOTEL_SERVICE_NAME=checkout-api\n' > "$TMP/otel-java.env"
INPUT="{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"$TMP/otel-java.env\"}}"
actual_exit=0
echo "$INPUT" | bash "$HOOK" > /dev/null 2>&1 || actual_exit=$?
if [ "$actual_exit" -eq 2 ]; then
  echo "PASS: block existing otel-java.env"
  PASS=$((PASS+1))
else
  echo "FAIL: block existing otel-java.env (expected 2, got $actual_exit)"
  FAIL=$((FAIL+1))
fi
rm -rf "$TMP"

# Test 10: no python interpreter available → FAIL CLOSED (block, exit 2), even for a file that
# would normally be ALLOWED (a brand-new non-OTel file). Proves the guard never silently fails
# open when it can't parse the payload. OTEL_HOOK_PYTHON= forces the missing-interpreter path.
INPUT='{"tool_name":"Write","tool_input":{"file_path":"src/brand-new.js"}}'
actual_exit=0
echo "$INPUT" | OTEL_HOOK_PYTHON= bash "$HOOK" > /dev/null 2>&1 || actual_exit=$?
if [ "$actual_exit" -eq 2 ]; then
  echo "PASS: fail closed (block) when python is unavailable"
  PASS=$((PASS+1))
else
  echo "FAIL: fail-closed on missing python (expected 2, got $actual_exit)"
  FAIL=$((FAIL+1))
fi

# Test 10b (#33): an interpreter that RESOLVES but does not RUN (the Windows Store `python3`
# alias stub: on PATH, `command -v` succeeds, but executing it errors) must FAIL CLOSED, not
# silently allow the write. Simulate the stub with an executable that exits non-zero, pointed to
# via OTEL_HOOK_PYTHON. Target a brand-new file that would otherwise be ALLOWED, so a pass here
# can only mean the guard blocked because it could not verify — not because the file was protected.
STUBDIR=$(mktemp -d)
printf '#!/bin/sh\necho "Python was not found; run without arguments to install from the Microsoft Store" >&2\nexit 9\n' > "$STUBDIR/python3-stub"
chmod +x "$STUBDIR/python3-stub"
INPUT='{"tool_name":"Write","tool_input":{"file_path":"src/brand-new.js"}}'
actual_exit=0
echo "$INPUT" | OTEL_HOOK_PYTHON="$STUBDIR/python3-stub" bash "$HOOK" > /dev/null 2>&1 || actual_exit=$?
if [ "$actual_exit" -eq 2 ]; then
  echo "PASS: fail closed (block) when the interpreter resolves but does not run (stub)"
  PASS=$((PASS+1))
else
  echo "FAIL: fail-closed on non-functional interpreter stub (expected 2, got $actual_exit)"
  FAIL=$((FAIL+1))
fi
rm -rf "$STUBDIR"

# --- Issue 13: the protected set is derived, not hand-listed -----------------------------
# telemetry.ts is generated by this plugin for every TypeScript project and used to be
# absent from the guard's hand-maintained basename list (only telemetry.js / telemetry.py
# were there), leaving the more valuable of the two generated files unprotected.
expect_blocked() {
  local name="$1"
  local tmp; tmp=$(mktemp -d)
  printf '# generated by otel-as-code v0.1.0\nexisting content\n' >"$tmp/$name"
  local input="{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"$tmp/$name\"}}"
  local rc=0
  echo "$input" | bash "$HOOK" > /dev/null 2>&1 || rc=$?
  if [ "$rc" -eq 2 ]; then
    echo "PASS: protects existing $name"; PASS=$((PASS+1))
  else
    echo "FAIL: protects existing $name (expected 2, got $rc)"; FAIL=$((FAIL+1))
  fi
  rm -rf "$tmp"
}

for name in telemetry.ts telemetry.go tracing.mjs opentelemetry.py tracing.rb; do
  expect_blocked "$name"
done

# ...and the derivation must not swallow unrelated files whose name merely contains a stem.
TMP=$(mktemp -d)
echo "app code" > "$TMP/request-tracing.js"
INPUT="{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"$TMP/request-tracing.js\"}}"
actual_exit=0
echo "$INPUT" | bash "$HOOK" > /dev/null 2>&1 || actual_exit=$?
if [ "$actual_exit" -eq 0 ]; then
  echo "PASS: leaves unrelated request-tracing.js alone"
  PASS=$((PASS+1))
else
  echo "FAIL: unrelated request-tracing.js (expected 0, got $actual_exit)"
  FAIL=$((FAIL+1))
fi
rm -rf "$TMP"

# --- Issue 12: --force must survive a path-shape mismatch --------------------------------
# The tool reports file_path in the host's convention while the sentinel is written from a
# shell that may spell the same file differently. An exact string compare (grep -Fxq) can
# never match across those shapes, so --force silently did nothing on Windows.
#
# force_shape <label> <sentinel line, %s = the real path> — asserts the overwrite is allowed.
force_shape() {
  local label="$1" line="$2"
  if [ "$IS_MSYS" = 1 ] && case "$2" in *%s*) true ;; *) false ;; esac; then
    echo "SKIP (MSYS, absolute temp path): --force honours $label"; return
  fi
  local tmp; tmp=$(mktemp -d)
  mkdir -p "$tmp/api/src" "$tmp/.claude"
  printf '# generated by otel-as-code v0.1.0\nexisting content\n' >"$tmp/api/src/tracing.ts"
  # shellcheck disable=SC2059
  printf "$line\n" "$tmp" > "$tmp/.claude/.otel-force"
  local input="{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"$tmp/api/src/tracing.ts\"}}"
  local rc=0
  echo "$input" | CLAUDE_PROJECT_DIR="$tmp" bash "$HOOK" > /dev/null 2>&1 || rc=$?
  if [ "$rc" -eq 0 ]; then
    echo "PASS: --force honours $label"; PASS=$((PASS+1))
  else
    echo "FAIL: --force honours $label (expected 0, got $rc)"; FAIL=$((FAIL+1))
  fi
  rm -rf "$tmp"
}

force_shape "a project-relative entry"        "api/src/tracing.ts"
force_shape "a ./-prefixed entry"             "./api/src/tracing.ts"
force_shape "an entry with . and .. segments" "%s/api/../api/./src/tracing.ts"
force_shape "trailing whitespace"             "%s/api/src/tracing.ts   "

# The Windows case, exercised on any host: the guard sees a backslashed drive path and the
# sentinel holds the Git Bash spelling of the same file. Both are normalised to /c/... so
# they compare equal — this is the exact pair that could never match before.
WIN_TOOL='C:\Users\JC\Repos\portal\api\src\tracing.ts'
WIN_SENTINEL='/c/Users/JC/Repos/portal/api/src/tracing.ts'
if python3 - "$WIN_TOOL" "$WIN_SENTINEL" <<'PY'
import subprocess, sys, tempfile, os
tool, sentinel = sys.argv[1], sys.argv[2]
d = tempfile.mkdtemp()
f = os.path.join(d, "force")
open(f, "w").write(sentinel + "\n")
sys.exit(subprocess.run(
    ["python3", "hooks/otel-force-match.py", tool, "/c/Users/JC/Repos/portal", f]
).returncode)
PY
then
  echo "PASS: --force matches a Windows path against its Git Bash spelling"
  PASS=$((PASS+1))
else
  echo "FAIL: --force matches a Windows path against its Git Bash spelling"
  FAIL=$((FAIL+1))
fi

# Teeth check: normalisation must not turn --force into a blanket disable. A sentinel
# naming a *different* file in the same directory still blocks.
force_shape_blocks() {
  local label="$1" line="$2"
  local tmp; tmp=$(mktemp -d)
  mkdir -p "$tmp/api/src" "$tmp/.claude"
  printf '# generated by otel-as-code v0.1.0\nexisting content\n' >"$tmp/api/src/tracing.ts"
  # shellcheck disable=SC2059
  printf "$line\n" "$tmp" > "$tmp/.claude/.otel-force"
  local input="{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"$tmp/api/src/tracing.ts\"}}"
  local rc=0
  echo "$input" | CLAUDE_PROJECT_DIR="$tmp" bash "$HOOK" > /dev/null 2>&1 || rc=$?
  if [ "$rc" -eq 2 ]; then
    echo "PASS: --force still blocks $label"; PASS=$((PASS+1))
  else
    echo "FAIL: --force still blocks $label (expected 2, got $rc)"; FAIL=$((FAIL+1))
  fi
  rm -rf "$tmp"
}

force_shape_blocks "a sibling file in the same dir" "%s/api/src/telemetry.ts"
force_shape_blocks "the same basename elsewhere"    "%s/web/src/tracing.ts"
force_shape_blocks "an empty sentinel"              ""

# --- Issue 7: the guard blocks only files WE generated, not any file that shares the name ----
# A candidate basename (tracing.js) that exists but carries NO ownership marker is someone
# else's hand-written file — overwriting it is the user's business, not ours. Blocking it was
# a false positive that made the plugin hostile to install in a repo with a pre-existing
# tracing.js. The marker is the sole authority on ownership.
TMP=$(mktemp -d)
echo "// hand-written, not ours" > "$TMP/tracing.js"
INPUT="{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"$TMP/tracing.js\"}}"
actual_exit=0
echo "$INPUT" | bash "$HOOK" > /dev/null 2>&1 || actual_exit=$?
if [ "$actual_exit" -eq 0 ]; then
  echo "PASS: leaves a markerless (hand-written) tracing.js alone"
  PASS=$((PASS+1))
else
  echo "FAIL: markerless tracing.js should not block (expected 0, got $actual_exit)"
  FAIL=$((FAIL+1))
fi
rm -rf "$TMP"

# --- Issue 3: TF protection is by basename in ANY directory, not just */observability/* ------
# /otel-backend --output-dir can land main.tf anywhere. The old path glob only caught
# */observability/*/main.tf, silently unprotecting every other layout. A marked main.tf in a
# custom directory must still block.
TMP=$(mktemp -d)
mkdir -p "$TMP/custom/infra/dd"
printf '# Generated by otel-as-code v0.1.0 on 2026-08-31.\nresource "x" "y" {}\n' > "$TMP/custom/infra/dd/main.tf"
INPUT="{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"$TMP/custom/infra/dd/main.tf\"}}"
actual_exit=0
echo "$INPUT" | bash "$HOOK" > /dev/null 2>&1 || actual_exit=$?
if [ "$actual_exit" -eq 2 ]; then
  echo "PASS: blocks a marked main.tf outside */observability/*"
  PASS=$((PASS+1))
else
  echo "FAIL: marked main.tf in a custom dir should block (expected 2, got $actual_exit)"
  FAIL=$((FAIL+1))
fi
rm -rf "$TMP"

# ...and the mirror: a markerless main.tf (a user's own Terraform) is never blocked, wherever
# it sits — the plugin must not hijack overwrite protection for infra it did not generate.
TMP=$(mktemp -d)
mkdir -p "$TMP/terraform"
echo 'resource "aws_s3_bucket" "mine" {}' > "$TMP/terraform/main.tf"
INPUT="{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"$TMP/terraform/main.tf\"}}"
actual_exit=0
echo "$INPUT" | bash "$HOOK" > /dev/null 2>&1 || actual_exit=$?
if [ "$actual_exit" -eq 0 ]; then
  echo "PASS: leaves a markerless (user-authored) main.tf alone"
  PASS=$((PASS+1))
else
  echo "FAIL: markerless main.tf should not block (expected 0, got $actual_exit)"
  FAIL=$((FAIL+1))
fi
rm -rf "$TMP"

# Test (#53): the --force match must use the RESOLVED working interpreter, not a hardcoded
# `python3`. Prepend a failing `python3` stub to PATH and point OTEL_HOOK_PYTHON at a real
# interpreter; a marked file listed in the sentinel must still be ALLOWED (exit 0). Before the
# fix, force-match shelled out to the stub `python3`, failed, and --force silently no-op'd → block.
REALPY=$(command -v python3 || true)
if [ -n "$REALPY" ]; then
  STUBDIR=$(mktemp -d)
  printf '#!/bin/sh\nexit 9\n' > "$STUBDIR/python3"; chmod +x "$STUBDIR/python3"
  TMP=$(mktemp -d)
  printf '# generated by otel-as-code v0.1.0\nx\n' > "$TMP/tracing.js"
  mkdir -p "$TMP/.claude"; echo "$TMP/tracing.js" > "$TMP/.claude/.otel-force"
  INPUT="{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"$TMP/tracing.js\"}}"
  actual_exit=0
  echo "$INPUT" | PATH="$STUBDIR:$PATH" OTEL_HOOK_PYTHON="$REALPY" CLAUDE_PROJECT_DIR="$TMP" bash "$HOOK" > /dev/null 2>&1 || actual_exit=$?
  if [ "$actual_exit" -eq 0 ]; then
    echo "PASS: --force match uses the resolved interpreter, not a hardcoded python3"
    PASS=$((PASS+1))
  elif [ "$IS_MSYS" = 1 ]; then
    echo "SKIP (MSYS, absolute temp path): force-match uses the resolved interpreter (#53)"
  else
    echo "FAIL: force-match still hardcodes python3 (#53) (expected 0, got $actual_exit)"
    FAIL=$((FAIL+1))
  fi
  rm -rf "$STUBDIR" "$TMP"
fi

echo ""
echo "Results: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
