# tracing.rb — OpenTelemetry SDK bootstrap, generated by otel-as-code v0.1.0
# Semconv version: 1.44.0
# Re-run /otel-instrument to regenerate.
require 'opentelemetry/sdk'
require 'opentelemetry/instrumentation/all'
require 'opentelemetry/exporter/otlp'

# Exports nowhere until OTEL_EXPORTER_OTLP_ENDPOINT is configured — the Ruby SDK's own default
# (no endpoint set) is NOT a no-op: it hardcodes http://localhost:4318 and retries with backoff,
# silently dropping telemetry with no log line for the common connection-refused case. Setting
# OTEL_TRACES_EXPORTER explicitly restores the same "exports nowhere until configured" guarantee
# every other language this plugin generates for already makes. Verified against
# opentelemetry-sdk 1.13.0 / opentelemetry-exporter-otlp 0.35.1 source plus a live run — do not
# remove this line or assume the SDK no-ops on its own.
ENV['OTEL_TRACES_EXPORTER'] ||= ENV['OTEL_EXPORTER_OTLP_ENDPOINT'] ? 'otlp' : 'none'

OpenTelemetry::SDK.configure do |c|
  c.service_name = ENV.fetch('OTEL_SERVICE_NAME', 'notifications-api')
  c.resource = OpenTelemetry::SDK::Resources::Resource.create({
    'service.version' => ENV.fetch('OTEL_SERVICE_VERSION', '1.1.0'),
    'service.namespace' => ENV.fetch('OTEL_SERVICE_NAMESPACE', 'storefront'),
    'deployment.environment.name' => ENV.fetch('DEPLOYMENT_ENV', 'development'),
  })
  c.use_all
end
