#!/usr/bin/env bash
# Guards: golden bootstraps stay syntactically valid AND their pins match
# agents/instrumentation-gen.md (the single source for OTel SDK versions).
set -uo pipefail
cd "$(dirname "$0")/../../.."   # repo root
pass=0; fail=0
check() { if eval "$2"; then echo "PASS: $1"; pass=$((pass+1)); else echo "FAIL: $1"; fail=$((fail+1)); fi; }

# pins_match <package.json path> — every "@opentelemetry/pkg": "version" pair captured
# from the given package.json must appear verbatim (full name+version pair, NOT just
# the package name) as a substring of agents/instrumentation-gen.md. Prints
# "  drift: <pair>" per miss; returns nonzero if any pair is missing.
pins_match() {
  local target="$1" miss=0 pair
  while IFS= read -r pair; do
    grep -qF "$pair" agents/instrumentation-gen.md || { echo "  drift: $pair"; miss=1; }
  done < <(grep -oE "\"@opentelemetry/[^\"]+\": \"[^\"]+\"" "$target")
  [ "$miss" -eq 0 ]
}

# pins_match_dotnet <csproj path> — every `Include="OpenTelemetry.*" Version="X"` PackageReference
# in the golden .csproj must have the package name AND that version together on some line of
# agents/instrumentation-gen.md (the generator prints `dotnet add package <name>  # <version>`).
# The .NET package strings differ between csproj and the `dotnet add` form, so this matches
# name+version on the same line rather than a verbatim substring like the Node check.
pins_match_dotnet() {
  local target="$1" miss=0 pkg ver
  while IFS='|' read -r pkg ver; do
    grep -F "$pkg" agents/instrumentation-gen.md | grep -qF "$ver" \
      || { echo "  drift: $pkg $ver"; miss=1; }
  done < <(grep -oE 'Include="OpenTelemetry[^"]*" Version="[^"]+"' "$target" \
             | sed -E 's/Include="([^"]+)" Version="([^"]+)"/\1|\2/')
  [ "$miss" -eq 0 ]
}

check "node bootstrap parses" 'node --check tests/snapshots/instrument/nodejs/tracing.js'
check "python bootstrap compiles" 'python3 -m py_compile tests/snapshots/instrument/python/tracing.py'
# every OTel pin (full name+version pair) in the golden package.json must appear in instrumentation-gen.md
check "node pins match generator" 'pins_match tests/snapshots/instrument/nodejs/package.json'

# Teeth check: proves pins_match actually compares versions, not just package names.
# Injects a version-only drift (^0.221.0 -> ^9.999.0) into a throwaway copy of the golden
# package.json and asserts pins_match correctly reports failure on it. Without this,
# a name-only check (the bug this fix addresses) would silently pass here too.
check "pin guard catches version drift (teeth check)" '
  tmp=$(mktemp -d)
  sed -E "s/(\"@opentelemetry\/sdk-node\": \")\^0\.222\.0\"/\1^9.999.0\"/" tests/snapshots/instrument/nodejs/package.json > "$tmp/package.json"
  drift_injected=0
  grep -qF "\"@opentelemetry/sdk-node\": \"^9.999.0\"" "$tmp/package.json" && drift_injected=1
  guard_caught_drift=0
  if [ "$drift_injected" -eq 1 ] && ! pins_match "$tmp/package.json" >/dev/null; then
    guard_caught_drift=1
  fi
  rm -rf "$tmp"
  [ "$drift_injected" -eq 1 ] && [ "$guard_caught_drift" -eq 1 ]'

# Java golden agent config: required OTEL_* keys present + gRPC protocol (paired with :4317
# throughout the plugin; the agent's own default is http/protobuf:4318, so grpc must be explicit).
check "java golden otel-java.env has required keys + grpc" '
  f=tests/snapshots/instrument/java/otel-java.env
  grep -q "^OTEL_SERVICE_NAME=" "$f" \
    && grep -q "deployment.environment.name=" "$f" \
    && grep -q "^OTEL_EXPORTER_OTLP_ENDPOINT=" "$f" \
    && grep -q "^OTEL_EXPORTER_OTLP_PROTOCOL=grpc$" "$f"'

# The pinned OTel Java agent version the e2e harness downloads (run.sh) must match the
# generator doc (agents/instrumentation-gen.md), so the two never drift apart.
check "java agent version pin matches generator" '
  v=$(grep -oE "OTEL_JAVA_AGENT_VERSION=[0-9.]+" tests/e2e/run.sh | head -1 | cut -d= -f2)
  [ -n "$v" ] && grep -qF "$v" agents/instrumentation-gen.md'

# .NET golden extension: carries the ownership marker (what the write-guard keys on), exposes the
# AddOtelObservability DI extension, and wires both signal pipelines. csc is not run here (offline
# lint job, no NuGet restore) — compilation is verified against a real ASP.NET Core project during
# development and by the e2e follow-up; this is the Java-style structural guard.
check ".NET golden has marker + extension signature + both pipelines" '
  f=tests/snapshots/instrument/dotnet/OpenTelemetry.cs
  grep -qi "generated by otel-as-code" "$f" \
    && grep -qF "IServiceCollection AddOtelObservability" "$f" \
    && grep -qF ".AddOpenTelemetry()" "$f" \
    && grep -qF ".WithTracing(" "$f" \
    && grep -qF ".WithMetrics(" "$f"'

# The golden .csproj name is the guarded PascalCase artifact; and every OTel package pin in it
# must match agents/instrumentation-gen.md (name+version on one line).
check ".NET pins match generator" 'pins_match_dotnet tests/snapshots/instrument/dotnet/checkout-api.csproj'

# Teeth check: prove pins_match_dotnet compares versions, not just names — inject a version-only
# drift into a throwaway copy of the golden csproj and assert the guard reports failure.
check ".NET pin guard catches version drift (teeth check)" '
  tmp=$(mktemp -d)
  sed -E "s/(Include=\"OpenTelemetry.Instrumentation.Http\" Version=\")1\.18\.0\"/\1""9.999.0\"/" \
    tests/snapshots/instrument/dotnet/checkout-api.csproj > "$tmp/x.csproj"
  drift_injected=0
  grep -qF "Include=\"OpenTelemetry.Instrumentation.Http\" Version=\"9.999.0\"" "$tmp/x.csproj" && drift_injected=1
  guard_caught=0
  if [ "$drift_injected" -eq 1 ] && ! pins_match_dotnet "$tmp/x.csproj" >/dev/null; then guard_caught=1; fi
  rm -rf "$tmp"
  [ "$drift_injected" -eq 1 ] && [ "$guard_caught" -eq 1 ]'

echo "Results: $pass passed, $fail failed"
[ "$fail" -eq 0 ]
