#!/usr/bin/env bash
# hooks/session-summary.sh
# SessionEnd hook — emits OTel session changelog for PR descriptions.
# Always exits 0.

set -euo pipefail

# Collect otel-as-code generated files that actually CHANGED in the working tree.
CHANGED_OTEL=()

# Is this an otel-as-code generated artifact? Matches anywhere in the path so monorepo
# locations (e.g. packages/foo/tracing.js) are covered.
is_otel_path() {
  case "$1" in
    *tracing.js|*tracing.ts|*tracing.py|*opentelemetry.js|*opentelemetry.ts|*telemetry.js|*telemetry.py) return 0 ;;
    *otelcol-agent.yaml|*otelcol-gateway.yaml) return 0 ;;
    */observability/*/main.tf) return 0 ;;
    *.claude/otel-context.json|*.claude/otel-services.json) return 0 ;;
    *) return 1 ;;
  esac
}

if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  # Git is authoritative: report only files changed this session (staged, unstaged, or new).
  # Strip the 2-char status + space prefix; for renames keep the post-`->` path.
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    if is_otel_path "$f"; then CHANGED_OTEL+=("$f"); fi
  done < <(git status --porcelain=v1 --untracked-files=all 2>/dev/null | sed -e 's/^...//' -e 's/.* -> //')
else
  # Not a git repo — fall back to scanning known locations that exist on disk.
  for f in tracing.js tracing.ts tracing.py src/tracing.js src/tracing.ts src/tracing.py \
           opentelemetry.js telemetry.js otelcol-agent.yaml otelcol-gateway.yaml \
           .claude/otel-context.json .claude/otel-services.json; do
    [ -f "$f" ] && CHANGED_OTEL+=("$f")
  done
  for vendor in grafana datadog newrelic dash0; do
    [ -f "infra/observability/${vendor}/main.tf" ] && CHANGED_OTEL+=("infra/observability/${vendor}/main.tf")
  done
fi

if [ "${#CHANGED_OTEL[@]}" -eq 0 ]; then
  exit 0  # Nothing OTel-related changed; no summary needed
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  otel-as-code session summary (for PR description)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "## Observability changes"
echo ""

for f in "${CHANGED_OTEL[@]}"; do
  case "$f" in
    *tracing.js|*tracing.ts)
      echo "- Added Node.js OTel SDK bootstrap (\`$f\`)" ;;
    *tracing.py)
      echo "- Added Python OTel SDK bootstrap (\`$f\`)" ;;
    *otelcol-agent.yaml)
      echo "- Added OTel Collector agent config (\`$f\`)" ;;
    *otelcol-gateway.yaml)
      echo "- Added OTel Collector gateway config (\`$f\`)" ;;
    *grafana/main.tf)
      echo "- Added Grafana Cloud observability module (\`$f\`)" ;;
    *datadog/main.tf)
      echo "- Added Datadog observability module (\`$f\`)" ;;
    *newrelic/main.tf)
      echo "- Added New Relic observability module (\`$f\`)" ;;
    *dash0/main.tf)
      echo "- Added Dash0 observability module (\`$f\`)" ;;
    *.claude/otel-services.json)
      echo "- Updated service map (\`$f\`)" ;;
    *opentelemetry.js|*opentelemetry.ts|*telemetry.js|*telemetry.py)
      echo "- Updated OTel instrumentation (\`$f\`)" ;;
    *.claude/otel-context.json)
      echo "- Updated context cache (\`$f\`)" ;;
    *)
      # Catch-all: anything is_otel_path() counted must still get a bullet, so the
      # summary header is never emitted with an empty body.
      echo "- Updated OTel file (\`$f\`)" ;;
  esac
done

echo ""
echo "Generated by [otel-as-code](https://github.com/YOUR_ORG/otel-as-code)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

exit 0
