#!/usr/bin/env bash
# hooks/session-summary.sh
# SessionEnd hook — emits OTel session changelog for PR descriptions.
# Always exits 0.

set -euo pipefail

# Generated-file vocabulary, shared with write-guard.sh so the two cannot drift: a file the
# guard protects is a file this summary reports.
# Guarded so a broken install cannot violate this hook's always-exit-0 contract.
# shellcheck source=hooks/otel-paths.sh
if ! . "$(dirname "${BASH_SOURCE[0]}")/otel-paths.sh" 2>/dev/null; then
  exit 0  # no vocabulary, nothing to report; never fail a SessionEnd hook
fi

# Collect otel-as-code generated files that actually CHANGED in the working tree.
CHANGED_OTEL=()

# Is this an otel-as-code generated artifact? Basename matching covers monorepo locations
# (e.g. packages/foo/tracing.js) without also claiming a user's `request-tracing.js`.
is_otel_path() {
  if otel_is_generated_path "$1"; then return 0; fi
  case "$1" in
    */observability/*/main.tf) return 0 ;;
    *.claude/otel-context.json|*.claude/otel-services.json) return 0 ;;
    *) return 1 ;;
  esac
}

if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  # Git is authoritative: report otel-as-code generated files currently changed in the working
  # tree (staged, unstaged, or untracked) — this is the whole dirty tree, not scoped to a session.
  # Strip the 2-char status + space prefix; for renames keep the post-`->` path.
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    if is_otel_path "$f"; then CHANGED_OTEL+=("$f"); fi
  done < <(git status --porcelain=v1 --untracked-files=all 2>/dev/null | sed -e 's/^...//' -e 's/.* -> //')
else
  # Not a git repo — fall back to scanning known locations that exist on disk. The file
  # names come from otel-paths.sh rather than a second hand-kept list.
  while IFS= read -r name; do
    for rel in "$name" "src/$name" "app/$name"; do
      [ -f "$rel" ] && CHANGED_OTEL+=("$rel")
    done
  done < <(otel_bootstrap_globs)
  for f in .claude/otel-context.json .claude/otel-services.json; do
    [ -f "$f" ] && CHANGED_OTEL+=("$f")
  done
  # Supported backends come from the plugin's single source of truth (backends.txt).
  # Guarded so a missing file can never break this always-exit-0 hook.
  PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
  for vendor in $(cat "$PLUGIN_ROOT/backends.txt" 2>/dev/null || true); do
    [ -f "infra/observability/${vendor}/main.tf" ] && CHANGED_OTEL+=("infra/observability/${vendor}/main.tf")
  done
fi

if [ "${#CHANGED_OTEL[@]}" -eq 0 ]; then
  exit 0  # Nothing OTel-related changed; no summary needed
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  otel-as-code session summary (for PR description)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "## Observability changes"
echo ""

for f in "${CHANGED_OTEL[@]}"; do
  case "$f" in
    *tracing.js|*tracing.ts|*tracing.mjs|*tracing.cjs|*tracing.mts|*tracing.cts)
      echo "- Added Node.js OTel SDK bootstrap (\`$f\`)" ;;
    *tracing.py)
      echo "- Added Python OTel SDK bootstrap (\`$f\`)" ;;
    *otel-java.env)
      echo "- Added OpenTelemetry Java agent config (\`$f\`)" ;;
    *otelcol-agent.yaml)
      echo "- Added OTel Collector agent config (\`$f\`)" ;;
    *otelcol-gateway.yaml)
      echo "- Added OTel Collector gateway config (\`$f\`)" ;;
    *grafana/main.tf)
      echo "- Added Grafana Cloud observability module (\`$f\`)" ;;
    *datadog/main.tf)
      echo "- Added Datadog observability module (\`$f\`)" ;;
    *newrelic/main.tf)
      echo "- Added New Relic observability module (\`$f\`)" ;;
    *dash0/main.tf)
      echo "- Added Dash0 observability module (\`$f\`)" ;;
    *.claude/otel-services.json)
      echo "- Updated service map (\`$f\`)" ;;
    *opentelemetry.*|*telemetry.*)
      echo "- Updated OTel instrumentation (\`$f\`)" ;;
    *.claude/otel-context.json)
      echo "- Updated context cache (\`$f\`)" ;;
    *)
      # Catch-all: anything is_otel_path() counted must still get a bullet, so the
      # summary header is never emitted with an empty body.
      echo "- Updated OTel file (\`$f\`)" ;;
  esac
done

echo ""
echo "Generated by [otel-as-code](https://github.com/radra23/otel-as-code-plugin)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

exit 0
