// OpenTelemetry instrumentation — generated by otel-as-code v0.1.0
// Semconv version: 1.44.0
// Re-run /otel-instrument to regenerate.
//
// One-time wiring — add this line to Program.cs before builder.Build():
//     builder.Services.AddOtelObservability(builder.Configuration);
using OpenTelemetry.Metrics;
using OpenTelemetry.Resources;
using OpenTelemetry.Trace;

namespace CheckoutApi.Observability;

public static class OtelObservability
{
    public static IServiceCollection AddOtelObservability(
        this IServiceCollection services, IConfiguration configuration)
    {
        // service.name defaults to the confirmed value but is overridable via OTEL_SERVICE_NAME.
        // deployment.environment.name reads DEPLOYMENT_ENV at runtime so one build promotes across
        // environments; falls back to "development" when unset.
        var serviceName = configuration["OTEL_SERVICE_NAME"] ?? "checkout-api";
        var deploymentEnv = configuration["DEPLOYMENT_ENV"] ?? "development";

        // The OTLP exporter reads OTEL_EXPORTER_OTLP_ENDPOINT / _PROTOCOL from the environment.
        // With no endpoint set it defaults to http://localhost:4317 — the deployment MUST set the
        // endpoint (see /otel-instrument Step 8) or spans go nowhere.
        services.AddOpenTelemetry()
            .ConfigureResource(resource => resource
                .AddService(serviceName: serviceName, serviceVersion: "1.4.2")
                .AddAttributes(new KeyValuePair<string, object>[]
                {
                    new("service.namespace", "checkout"),
                    new("deployment.environment.name", deploymentEnv),
                }))
            .WithTracing(tracing => tracing
                .AddAspNetCoreInstrumentation()
                .AddHttpClientInstrumentation()
                .AddOtlpExporter())
            .WithMetrics(metrics => metrics
                .AddAspNetCoreInstrumentation()
                .AddHttpClientInstrumentation()
                .AddOtlpExporter());

        return services;
    }
}
